name: Deploy playground

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: ğŸš€ Deploy
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: âš™ï¸ Get Node.js version
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: ğŸ—ï¸ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: ğŸ“„ Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: ğŸ“¦ Install packages
        run: npm ci
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: ğŸ‘· Build packages
        run: npm run build

      - name: â¬†ï¸ Upload playground
        uses: actions/upload-pages-artifact@v1
        with:
          path: './playground/dist'

      - name: ğŸš€ Deploy
        id: deployment
        uses: actions/deploy-pages@v2
